name: Continuous Integration
run-name: CI

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Tidy
        run: go mod tidy
      - name: App Version
        run: go run main.go version
  